[package]
name = "hekhat"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tui = "0.19"
crossterm = "0.24"
serde = "1.0"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
chrono = "0.4"


[features]
client = []
